FROM die-web-runtime:latest

RUN rm -rf /usr/share/nginx/html/* && mkdir -p /usr/share/nginx/html/scan-engine /usr/share/nginx/html/signatures-pack
COPY web/dist             /usr/share/nginx/html/
COPY scan-wasm/dist       /usr/share/nginx/html/scan-engine/
COPY signatures-pack/dist /usr/share/nginx/html/signatures-pack/
COPY docker/nginx.conf    /etc/nginx/conf.d/default.conf
EXPOSE 80
